name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    
    strategy:
      matrix:
        php-version: [7.4, 8.0, 8.1, 8.2, 8.3]
        laravel-version: [6, 7, 8, 9, 10, 11]
        exclude:
          - php-version: 7.4
            laravel-version: 11
          - php-version: 8.0
            laravel-version: 11
          - php-version: 8.1
            laravel-version: 11

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, curl, json

    - name: Install dependencies
      run: |
        # Remove composer.lock to force fresh resolution for each PHP/Laravel combination
        rm -f composer.lock
        composer install --prefer-dist --no-progress --no-interaction

    - name: Run tests
      run: composer test

  release:
    runs-on: ubuntu-latest
    name: Create Release
    needs: test
    
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.3
        extensions: mbstring, xml, curl, json

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-interaction

    - name: Run tests
      run: composer test

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  packagist:
    runs-on: ubuntu-latest
    name: Update Packagist
    needs: release
    
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update Packagist
      run: |
        echo "Updating Packagist..."
        echo "Username: ${{ secrets.PACKAGIST_USERNAME }}"
        echo "Token: ${{ secrets.PACKAGIST_TOKEN }}"
        
        if [ -z "${{ secrets.PACKAGIST_USERNAME }}" ] || [ -z "${{ secrets.PACKAGIST_TOKEN }}" ]; then
          echo "❌ PACKAGIST_USERNAME or PACKAGIST_TOKEN secrets are not set!"
          echo "Please add these secrets in GitHub repository settings."
          exit 1
        fi
        
        curl -X POST "https://packagist.org/api/update-package?username=${{ secrets.PACKAGIST_USERNAME }}&apiToken=${{ secrets.PACKAGIST_TOKEN }}" \
          -d "repository[url]=https://github.com/Ekatra-Global-Corp/ekatra-php-sdk.git" \
          -H "Content-Type: application/x-www-form-urlencoded"
        
        echo "✅ Packagist update request sent successfully!"
